language: node_js
node_js:
  - "7"
jobs:
  include:
    - stage: test
      install: npm install
      script:
        - npm run build
        - npm run lint
        - npm run test:unit
        - npm run test:integration
    - stage: test
      install:
        - npm install
        - ./.travis/build_e2e_tests.sh
      script: ./.travis/run_e2e_tests.sh
    - stage: deploy
      install: npm install
      script: skip
      before_deploy:
        - npm run build
      deploy:
        - provider: npm
          skip_cleanup: true
          email: dongha.kim210@gmail.com
          api_key:
          - secure: UJCuatBn0Oencga2bUrtMkqZlCWtGyDPSOX+3hRcraWZ/k45Us3sWxpn0ttCOOrIjTlqkCVGD0od5CKNRNgQXeAsXqw6RgIYCKXiQCWubHqOdiUoJq3oPxp98wgTx2wZRkurJeSdk4dpWYZVJB4whGjitpjBGd3/HbirBU4j2m5jBWJCjTHeA0RA7QOTUk7KzNa9AgNoWM8sQuu9FbfRkmDv1YF6cWSFHyjSp9E/qU9nP82oA65tVasBdwSxEHHcTjry8YXKqhfMkieKOhGmyRwxI4HpEp57iW+4bfruFuBosNWkx9neNGuGHn9jxXxKKjk475GFSRzV2tF1uwYBY0cNDD98kxbwqmdmxyLskejCzEKhal61qrgeQNCcnBGwvtMYoptBJVtCt32/KvE8v4TdjQBRKsCXmmemN6mczttP6LAALDpOm+UkU+qBRUcxf4kRWkvkSOlBp5Q68Awv1tcPERsoYVo9wrCX29zOcn1Ngl0eVvfoV2djmXKAkIR6KGBvg3K3sD+K8qgTE2oXXX3SHGfzGQieTlgR8uJD9Y/ZrwCYXOEc+sWdLlXotk2UpgKPz3llSyVYV1pnwe7OURbsYxXR7Mr7CaUExUs8KQjMNpbGlW70+UOW0HOsYm/T+pNklfpNNnRPTKDuN0oTFqUN584vwYe52KcF/Z90jEA=
          on:
            tags: true
            branch: develop
        - provider: script
          skip_cleanup: true
          script: ./node_modules/.bin/fluid-publish cleanCmd
          tag: next
          on:
            branch: feature/fluid-publish-npm
branches:
  only:
  - master
  - develop
  - feature/fluid-publish-npm
services:
  - docker
cache:
  directories:
    - "node_modules"
notifications:
  webhooks:
    urls:
      - secure: "R7leHfENzyd6mAIdDS1JUmwZnvuG8QSgQfcjH6QGzh7c1UlUJHrP+u5G5fiWGB4mBNQexh1nOpW8+JlYFyEnWrXUgg2wXDhLxM45jaVmgpYmusNvLC+fk70o4k6KksSYOkoo2pxcthlsp2BqCfkVA8f1dxy7Q6RxQBp4KBoWfh+qQ00fCp/OsL/UuPlYz5qWohxAVyulIVVfvEWlplH870nE/VZD+K91KIB6CDBR1REjx4ZBq904jsD4sg4cYua7Rik6F1grfA84Lt68s2gG89d11qhMtkEE6ROU++N3ziOFNbQIWVMTHW0JqcCLZ+cbvLH48m3IeOhttkdjE0JbzK3WsmYlHlxkZGmqyxucYxAd9nODkxKRjcrc+OFKgQ359HyWBwf9AtHi6mPhrMGrOEcTPxNi+ZGpnYQgqlJ+akW2cXO/fcw6bLYU+i535MgGG6oqotkfS6k7IkZBnkw3ly9AwJ1n9XUHALKF21GtcCMGdSkUtQtnLUFxO0Wg7GIbMXxDXrLw8CF56u6AQy75F+/5LDTdfLHWgZKO+G5HrHUsFuq6S6EydEH2WxVYaJ7XS5M8TIDzEr8ZQdtTG0LJA+Yb3YxzcPbIRomQrWIw8MXdk3eA5MjIZy0cwXMdNeqSgFpTba1Yg98HQfjjW78QV5VBAxXK+iv1T7oooChu51s="
    on_success: change
    on_failure: always
env:
  - secure: rqGV+/s48b8gf9XB5tQ9iZN7gP1vT05Twtx9X8Cp2afuRgn+dKaAv23znhieFVZZjO3UCrwozIZpWymHiPL5uVSzYkURVlNaWyTttpO93uN2Ip/zuw/kEm9PNgyYHCgzhVKeE14GCirc2F7BY2aUKWnvgTX8pH1QSpPhrRUoovHpJscwbZRIAFWSD0EDJwdH/1PZv7iqGqbnffPrEy9cxyHQhJdMmZNEmdcMBM6hWpXWkAirNLKJGlvNmsWFoMpXzxGBjZn9ig8FoZGnA9wuHoL8qXnJN6D2Qv/ppATUitPwqMSugbJFACUsgXqGnItFxMyfOHwCviUnpSSAQJPn+vWaWFvYx1Yfb/J0bM9dKmgFHjsoRpanAIUow8iqKNkAQtM15llW7N2/wmVxKo0fCLXISc4Wlv/Szcud6rtB6oIQC3zNQUkIuY4nU3DZQHdmJW7HNLzv72VtoTL/WSayKFhzCuWHEXfCNFuETcIIcO1Bx62IaaAybZ6X2mBX+32P6MbjjMjBm3J+f0xu5+5zZ+Ns+WGHIhxpE1Zt69RP4Zl1RosNhPFKmPgxfGaQ8WZ0mXXg/MYYP5ittDdu0CqrmsppA+QlLekHrG7QHRWPYXguFT3xKBcQiPG5wgEEzPISy2i02l3tRrD8xrqZwGKROFHyj4kBo+iI24iuzYu3LKU=
