version: 2.1

commands:
  yarn-install:
    description: "Install or restore cached dependencies and save cache."
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Saven Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  run-code-coverage:
    description: "Run code coverage and upload report."
    parameters:
      flag:
        type: string
    steps:
      - run: yarn coverage -F << parameters.flag >>

jobs:
  lint:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - yarn-install
      - run:
          name: Run linter
          command: yarn lint

  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - yarn-install
      - run:
          name: Build production
          command: yarn build

  unit-test:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - yarn-install
      - run:
          name: Run unit tests
          command: yarn test:unit
      - run-code-coverage:
          flag: unit


  integration-test:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - yarn-install
      - run: yarn test:integration
      - run-code-coverage:
          flag: integration

  e2e-test:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - yarn-install
      - run: 
          name: Build Docker Compose
          command: ./.circleci/build_e2e_tests.sh
      - run: 
          name: Start Docker Container and Run E2E Tests
          command: ./.circleci/run_e2e_tests.sh
      - run-code-coverage:
          flag: e2e

workflows:
  version: 2
  default:
    jobs:
      - lint
      - build
      - unit-test:
          requires:
            - lint
            - build
      - integration-test:
          requires:
            - lint
            - build
      - e2e-test:
          requires:
            - lint
            - build
